server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/customers/**
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/products/**

